site_name: Star Technology Wiki
site_url: https://github.com/StarT-Dev-Team/StarT-Wiki
repo_name: Star Technology
repo_url: https://github.com/StarT-Dev-Team/Star-Technology
use_directory_urls: true
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy 

  palette:
    #Â Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: light blue

markdown_extensions:
  - toc:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra_css:
  - assets/styles/styles.css

nav:
- Welcome to Star Technology:
  - Home: index.md
  - Patch Notes: Patch-Notes.md
  - Meet the Team:
      - Developer Team: 'Meet-the-Team/Developer-Team.md'
      - Credits: 'Meet-the-Team/Credits.md'
  - Contributing to this Wiki: 'Contributing-to-This-Wiki.md'

- Resource Gen:
    - Resource Production:
        - Hydrogen: 'Resources/Resource-Production/Hydrogen.md'
        - Nitrogen: 'Resources/Resource-Production/Nitrogen.md'
        - Oxygen: 'Resources/Resource-Production/Oxygen.md'
    - Resource Production Machine Lines:
        - Drilling Rigs: 'Resources/Resource-Production-Machines-Lines/Drilling Rigs.md'

- Power Gen:
    - Create Power: 'Mechanics/Energy-Generation/Carbon-Brushes-and-Magnets.md'

- Chemical/Processing Lines:
    - Plastics:
        - Polether Ether Ketone: Chemical-Lines/Plastics/PEEK.md
        - Polybenzimidazole: Chemical-Lines/Plastics/Polybenzimidazole.md
        - Polycaprolactam: Chemical-Lines/Plastics/Polycaprolactam.md
        - Polyethylene: Chemical-Lines/Plastics/Polyethylene.md
        - Polyphenylene Sulfide: Chemical-Lines/Plastics/Polyphenylene-Sulfide.md
        - Polytetrafluoroethylene: Chemical-Lines/Plastics/Polytetrafluoroethylene.md
        - Polyvinyl Butyral: Chemical-Lines/Plastics/Polyvinyl-Butyral.md
        - Polyvinyl Chloride: Chemical-Lines/Plastics/Polyvinyl-Chloride.md
    - Rubbers:
        - Latex Rubber: Chemical-Lines/Rubbers/Rubber.md
        - Silicone Rubber: Chemical-Lines/Rubbers/Silicone-Rubber.md
        - Styrene Butadiene: Chemical-Lines/Rubbers/Styrene-Butadiene.md
    - Acids: 
        - Acetic Acid: Chemical-Lines/Acids/Acetic-Acid.md
        - Formic Acid: Chemical-Lines/Acids/Formic-Acid.md
        - Hydrocloric Acid: Chemical-Lines/Acids/Hydrochloric-Acid.md
        - Hydrofluoric Acid: Chemical-Lines/Acids/Hydrofluoric-Acid.md
        - Nitric Acid: Chemical-Lines/Acids/Nitric-Acid.md
        - Sulfuric Acid: Chemical-Lines/Acids/Sulfuric-Acid.md   

- Multiblocks:
    - LV Multiblocks: Mechanics/GregTech/Multiblocks/LV/LV-Multis.md

- Logisitics:
    - LaserIO:
        - Introduction: Mechanics/LaserIO/LaserIO.md

    - AE2:
        - Introduction: Mechanics/Applied-Energistics-2/AE2-Introduction.md

- Gregtech Mechanics:
    - Electricity: Mechanics/GregTech/Energy.md

- FAQ/Troubleshooting:
    - Contribute: FAQ.md
