site_name: Star Technology Wiki
site_url: https://github.com/StarT-Dev-Team/StarT-Wiki
repo_name: Star Technology
repo_url: https://github.com/StarT-Dev-Team/Star-Technology
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.top
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy 

  palette:
    #Â Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: light blue

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:


extra_css:
  - assets/styles/styles.css

nav:
- Welcome to Star Technology:
  - Home: index.md
  - Patch Notes: Patch-Notes.md
  - Meet the Team:
      - Developer Team: 'Meet-the-Team\Developer-Team.md'
      - Credits: 'Meet-the-Team\Credits.md'
  - Contributing to this Wiki: 'Contributing-to-This-Wiki.md'

- Resource Gen:
    - Resource Production:
        - Hydrogen: 'Resources\Resource Production\Hydrogen.md'
        - Nitrogen: 'Resources\Resource Production\Nitrogen.md'
        - Oxygen: 'Resources\Resource Production\Oxygen.md'
    - Resource Production Machine Lines:
        - Drilling Rigs: 'Resources\Resource Production Machines Lines\Drilling Rigs.md'

- Power Gen:
    - Contribute: 'docs\Contributing-to-This-Wiki.md'

- Chemical/Processing Lines:
    - Plastics:
        - PEEK: 'Chemical-Lines\Plastics\PEEK.md'
- Multiblocks:
    - Contribute: 'docs/Contributing-to-This-Wiki.md'
- AE2:
    - Contribute: 'docs/Contributing-to-This-Wiki.md'
- Gregtech Mechanics:
    - Contribute: 'docs/Contributing-to-This-Wiki.md'
- FAQ/Troubleshooting:
    - Contribute: 'docs/Contributing-to-This-Wiki.md'